// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"3d3gbpl2p3","name":"sampleCloudApi","description":"","endpoint":"https://3d3gbpl2p3.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]},{"id":"ir0b2r9eo8","name":"notificationsCRUD","description":"","endpoint":"https://ir0b2r9eo8.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/notifications","/notifications/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:168c8085-1179-491f-8f48-3d10cf935233',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'smartonepmapp-hosting-mobilehub-1576140790',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1khit2k3gs1tz.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"smartonepmapp-mobilehub-1576140790-notifications","attributes":[{"name":"community_id","type":"S"},{"name":"from","type":"S"},{"name":"buildings","type":"M"},{"name":"created","type":"N"},{"name":"effective","type":"N"},{"name":"expires","type":"N"},{"name":"external_id","type":"S"},{"name":"message","type":"S"},{"name":"message_id","type":"S"},{"name":"status","type":"S"},{"name":"subject","type":"S"},{"name":"type","type":"S"},{"name":"units","type":"M"}],"indexes":[],"region":"us-east-1","hashKey":"community_id","rangeKey":"from"}],
    'aws_mobile_analytics_app_id': '7906bd76076f4429a1e75f6ce4b17c22',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '2aaeb26e-9191-48e2-a046-a3c8c1e6f2c9',
    'aws_project_name': 'smartone-pm-app',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'smartonepmapp-deployments-mobilehub-1576140790',
    'aws_resource_name_prefix': 'smartonepmapp-mobilehub-1576140790',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_NYzdxYRcS',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '36bosu4hpt0vm93jdjcld0ip6i',
}

export default awsmobile;
